<?php
    echo $this->doctype();
    $basePath = $this->basePath();

    /*      Favicon image */
    $this->headLink(array(
    'rel'  => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $basePath . '/favicon.ico',
    ));

    /*   apple-touch-icon.png       */
    $this->headLink(array(
    'rel'  => 'shortcut icon',
    'href' => $basePath . '/images/apple-touch-icon.png',
    ));
    ?>

    <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
    <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
    <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
    <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); 
                       $this->headTitle()->setSeparator(' - ') ->setAutoEscape(false);
                  echo $this->headTitle('Wahlqvist Web') ?>



        <?php
            $this->headLink()->prependStylesheet($this->basePath() . 'css/main.css');
            $this->headLink()->appendStylesheet($basePath . 'css/normalize.css');
            $this->headLink()->appendStylesheet('http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css');
        
         
        
            $this->headScript()->appendFile($basePath . 'js/vendor/modernizr-2.6.2.min.js')
                               ->appendFile($basePath . '//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js')
                               ->appendFile($basePath . 'js/plugins.js')
                               ->appendFile($basePath . 'js/main.js')
                               ->appendFile($basePath . 'http://code.jquery.com/jquery-1.8.2.min.js')
                               ->appendFile($basePath . 'http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js');
                                
        ?>
        
        <!-- Styles -->
        <?php echo $this->headLink() ?>
        
        
        <!-- Scripts -->
        <?php echo $this->headScript() ?>
    
    </head>

    <body>
        
        <div class="container-fluid" id="container" data-role="page">

            <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
            <![endif]-->

            
            <div data-role="header" data-position="fixed" data-id="header"> 
                <h1>Wahlqvist Web</h1>    
            </div>
            
            
            <div data-role="navbar">
                <ul>
                    <li><a class="brand" href="<?php echo $this->url('home') ?>"  rel="external" data-icon="home">Home</a></li> 
                    <li><a href="<?php echo $this->url('contact') ?>"  rel="external" data-icon="info">Contact</a></li>
                </ul>
            </div>
            
                <div data-role="content">
                    <!-- Top of content -->
                        <?php echo $this->content; ?>
                    <!-- End of content -->
                </div>
            <div data-role="footer" data-position="fixed" data-id="footer"> 
                <h4>Wahlqvist Web</h4> 
            </div> 
               

        </div>


        <!-- Piwik --> 
            <script type="text/javascript">
                var pkBaseURL = (("https:" == document.location.protocol) ? "https://analytics.wahlqvist.co.uk/" : "http://analytics.wahlqvist.co.uk/");
                document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
                </script><script type="text/javascript">
                try {
                var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
                piwikTracker.trackPageView();
                piwikTracker.enableLinkTracking();
                } catch( err ) {}
            </script><noscript><p><img src="http://analytics.wahlqvist.co.uk/piwik.php?idsite=1" style="border:0" alt="" /></p></noscript>
        <!-- End Piwik Tracking Code -->
        
        
        
        
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-263309-26']);
            _gaq.push(['_setDomainName', 'wahlqvist.co.uk']);
            _gaq.push(['_trackPageview']);

            (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>

    </body>
</html>